name: 02 - Workflow Events
on:
    #  push:
    #  pull_request:
    #  schedule:
    #       - cron: "*/5 * * * *"
     workflow_dispatch:
          inputs:
               logLevel:
                    description: "Log level"
                    required: true
                    default: "warning"
                    type: choice
                    options:
                         - info
                         - warning
                         - debug
               tags:
                    description: "Test scenario tags"
                    required: false
                    type: boolean
               environment:
                    description: "Environment to run tests against"
                    type: environment
                    required: true
jobs:
     echo:
          runs-on: ubuntu-latest
          steps:
               - name: Show the trigger
                 run: echo ${{ github.event_name }}
     log-the-inputs:
        runs-on: ubuntu-latest
        steps:
            - run: |
                    echo "Log level: ${{ github.event.inputs.logLevel }}"
                    echo "Tags: ${{ github.event.inputs.tags }}"
                    echo "Environment: ${{ github.event.inputs.environment }}"
